server:
  port: 8082

spring:
  application:
    name: AUTH-SERVICE
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

grpc:
  server:
    port: 9090