server:
  port: 8082

spring:
  application:
    name: AUTH-SERVICE
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours

auth:
  gateway:
    private-key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEAySwsD24XDZZfVc9rkihW/pZ7zvaOoMgCYoQgmlZpesGPj3nI
      qi6o5Wt9NgAZTZWsX6FzD97J8O4IkeXshuD5uNHcv7jxaDXnEsajOg21RJZfUj88
      qrbARTfRDJDN8d/TV+NuHGGuwLcpb5Xsm8ufDb8NibTFDdcpNHmPzs5U8pacy7gO
      L9KPpoelwqOtluUN6cJxU9v8TiXi23LseGxk35RvEztDwXMrgk4mCCojgjgs46ej
      IS/nusGzNeN07f7rsPTwinyysBoiwi8pdcOVQnmIfm52KFQek2dyoucC+sVOen9T
      mP+4HRSYmDr5S2r8Nr6OPlnrEHpZwVPCN+04ywIDAQABAoIBAGyViRqzA4Jz/fVl
      RdzYJUy5kQ4/CvFBw/fE9YwYxEpcG88HnwYstUFP6X+yQfYcqbPcgyy3xixjbwDB
      KBANcv0NWaeqfbMQFS+PRB9bstHYkI7mTyqeBd3WqOGtb1v0wjCYM6DiIN8ofhca
      x2G4YJuc2gPQLOSxlC4cx0CLIlLlfzNoHdPSrWgKfU4R7b9nesOlCuXGXIPsNydG
      d9itchyr/OYAPizrCwPsinqvA7wzSduJqe7Fn8p0XMCewR+pXylDa280Azb4ftLz
      a2KPxqLVoFq3hPZi4TvfIZbI7Ph2e4F7oSiI9s41tx+GS1Eie9WQTSPsX3gcTprn
      Lcti86ECgYEA8fhF3xaN/B4xA4hRRO64ZT7ybo7TpjVvyHs7IE/iNiTckKPNw5JS
      yeFlLn1hWx/Knq6NPrga38tTqp4tRUWXBGkArysHG5A/CNmpUb63CSCRLx2dpIFA
      AFfneq7zH0IG3UvRY0ANpReaC8YLEpRcjt25A4HZ3pVRFC5ZVrALxlkCgYEA1NZR
      GifIE8uOVYMWeUNpppMp4BlGrF+ZaG/0Lod6sJLtwiOMGOeD54i953ecK8+6POMV
      OpeawFjFEicbtT+90Im4J5chRtwIgeDdRu7D4TSmQK7nQX5DaDe0f49BBdOch6zP
      s6vwJ2+Cwvky0aF2dWUXhyUqHx63zj4TaVOf28MCgYEAjk8GSP5q4yyehwVVRsVf
      jaxHyN4XfFlRNQfE7mwNDur/DdJI4gzcw/7cE0uKRp2b/VeLmqeMprJesqn01hjn
      iKB41ozn0T401G+vNXSFEcklmiBA5s9dZNZOPclHE8sxXlWJAGZboA0RfHstZ+/5
      v8yHU5i7Gj2XQddAk8tWIYECgYEAoo0wkd5SM7Qid/LPRjwTQ7JfqBUF4f59hsMC
      Zkr4jEUbK0vE4vxmxH2uNEsozlkvbvMsMny5JzBlCtEtm0ccbFnSeQI22wyPvsoD
      lfojRivU0dADNQT+7GinBUleqtmMUh7M3vdxSl0jLE/w3SQI+e4EgyYCPpRSY0UL
      xESm8csCgYEAh+2o1ihMDiKTKKvDQpXXdnK9Hu86YO8ppsPOWUFNLKagFP6YXdsV
      -----END RSA PRIVATE KEY-----