server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: BANKING_USER
    password: BankingPassword123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

security:
  jwt:
    internal-secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    public-key: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApERMGdiNGoNYk10qFP1N
IUChpcRoe7flXDpuHcT7E9XH6bD6MAsXir8dgPUp28iNOyV3VdoqsCUhriSLN/Oe
q9IbPb2nIFbJG8g+qh7cabj/yRMM3aH7/n+zKjAkT09/SLxPsdTRarRe1F19z3fa
c77dXSbAF0zkE+6nl5HC8KDaud8PwlbxjzAsT7HT4dRQbwEWd9DnhIaGa7O+bDkO
jjlgueH7Hm2T1NgPyr1Smyh2eDh0vUUKpyhDSrhjRJEDKTRkIie/QAOGwkAfrQc/
fLCLCtNoCZhG/F8T2n52TTjiTgPBOC24kcKXI8mh+mALTqOBsSLJO9huF3+Wgudt
lQIDAQAB
-----END PUBLIC KEY-----
"
    private-key: "-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCkREwZ2I0ag1iT
XSoU/U0hQKGlxGh7t+VcOm4dxPsT1cfpsPowCxeKvx2A9SnbyI07JXdV2iqwJSGu
JIs3856r0hs9vacgVskbyD6qHtxpuP/JEwzdofv+f7MqMCRPT39IvE+x1NFqtF7U
XX3Pd9pzvt1dJsAXTOQT7qeXkcLwoNq53w/CVvGPMCxPsdPh1FBvARZ30OeEhoZr
s75sOQ6OOWC54fsebZPU2A/KvVKbKHZ4OHS9RQqnKENKuGNEkQMpNGQiJ79AA4bC
QB+tBz98sIsK02gJmEb8XxPafnZNOOJOA8E4LbiRwpcjyaH6YAtOo4GxIsk72G4X
f5aC522VAgMBAAECggEAEoU0w1E8D3oxmWPOo9EvSgl8cDElypUgQfbAhZC48jKP
OJTgkFwfyl/j1q9Nid8htUJzIvXXDEcTdgveum84O40TzzE7z5SZVg2MqyeRmEXo
aOZB9BcYT0hcjewhm+ONqUi5/4XMGqi9bFoiHisYMSaa1K7Sx42+xVSKBrfDb9e0
s5A6SFOjABdAoK76f9zd6N2s6v8xtzoB+6B+B/6kj/nTdCsdxBJOI/8nGghVMK9o
2cCtjBNa2bih2jmXSURz35cM/wIAP8PdslMy6+UbZa/KnZLzsf7X9yNmdiHiUpen
lX69+/sKR9KiZwU93aAx0E1uCwFwNn1ktVfV2Gp4oQKBgQDN4zQQnagZNUEuBsEX
Z8KuiqXENBYveZOaLqLAK9PikbgnxsSmZAKvTMsJWzNncG2nPFEzxCUepMbyQAVe
vhccFRqdlP7P41XyW1xnAbvQke8jn19KuMqrT9iikM8uSRcoR6WCh6dzOXud2yQn
FqmxUlVYOzuV4EyMfnybLssVOQKBgQDMP7el11IwrHOpt01FBcis9BDW+HCEVhI8
UX25dlDZk5U7pvozvRU0n21EwfJebxDRNAU2WGekUupkK9/4eS5eiWo8+EBHDzSU
XFN7K0a+9OZ2/3EpByB7oH2EiFj2TdwDOhVeFqkL6Abe5Tl1G7LEiiwyYliW97XC
8e3pD7VXPQKBgQCVBbsNu8+MT2uaMPFaS5QyWdCaL0lPm6QmmVLb3d1DxU2SHOEB
vqni0Ka1YvnWCR6VSadM3NAxWftWJNi+NsDrZqsZHFtDhb0T6uT6+dpDoR2CnzyO
DStEzEp1gHM1gVntoc4+qImfcR/0pkWItXKmEn4LmvQKC4vctUDj4f7EoQKBgCul
riQliG3YXHs3La8DVmgHXBXkT38oOYtkSr64Vvy3+hseSreFv6NYMmyQGbAugeSC
/l4ntDY8ddRkP9+EXfFb4jUXQ/0rdawCsuBOVjb2dM2XNuJyoHFq0Yfh70jrSInz
/p71rrhZpCY7y/SHr8MqV9mIhK/2TYRUWOgGMFVtAoGBAJXExBeS1U4u/k88Yz3I
a8L6exZAa32v8p4n9VqBR+1FX0AsbsRCDO/fVanFbPWCOIG7Iil/UwwzXk254YHT
w0LaHBLLAoWn/N031YhhB/1GuVOVaBexEWwdEGWGKC8YzHu2874OJEOjUyyRzk7l
51UVZb8uxPfq1KqOYNo+3nXN
-----END PRIVATE KEY-----
"
    internal-auth-header: "X-Internal-Auth"
    authorization-header: "Authorization"
    token-prefix: "Bearer "
    token-expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.panda.authenService: DEBUG