version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-banking-db
    environment:
      - ORACLE_PWD=OraclePassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-scripts:/opt/oracle/scripts/startup
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/OraclePassword123@//localhost:1521/XE", "@/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5

  oracle-web:
    image: container-registry.oracle.com/database/ords:21.4.3
    container_name: oracle-web-interface
    depends_on:
      - oracle-db
    ports:
      - "8181:8181"
    environment:
      - DB_HOSTNAME=oracle-db
      - DB_PORT=1521
      - DB_SERVICENAME=XE
      - APEX_PUBLIC_USER_PASS=OraclePassword123
      - APEX_TABLESPACE=APEX
      - TEMP_TABLESPACE=TEMP
      - APEX_LISTENER_PASS=OraclePassword123
      - APEX_REST_PASS=OraclePassword123
      - PUBLIC_PASSWORD=OraclePassword123
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local

networks:
  default:
    name: banking-network
