server:
  port: 8081

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authen-service
              uri: lb://AUTHEN-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - GatewayAuthFilter
                - StripPrefix=1
                
            - id: mdm-service
              uri: lb://MDM-SERVICE
              predicates:
                - Path=/api/mdm/**
              filters:
                - GatewayAuthFilter
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

grpc:
  client:
    auth-service:
      address: static://localhost:9091
      negotiationType: PLAINTEXT

gateway:
  auth:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAySwsD24XDZZfVc9rkihW
      /pZ7zvaOoMgCYoQgmlZpesGPj3nIqi6o5Wt9NgAZTZWsX6FzD97J8O4IkeXshuD5
      uNHcv7jxaDXnEsajOg21RJZfUj88qrbARTfRDJDN8d/TV+NuHGGuwLcpb5Xsm8uf
      Db8NibTFDdcpNHmPzs5U8pacy7gOL9KPpoelwqOtluUN6cJxU9v8TiXi23LseGxk
      35RvEztDwXMrgk4mCCojgjgs46ejIS/nusGzNeN07f7rsPTwinyysBoiwi8pdcOV
      QnmIfm52KFQek2dyoucC+sVOen9TmP+4HRSYmDr5S2r8Nr6OPlnrEHpZwVPCN+04
      ywIDAQAB
      -----END PUBLIC KEY-----
