server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: mdm-service
          uri: lb://MDM-SERVICE
          predicates:
            - Path=/api/mdm/**
          filters:
            - StripPrefix=1
        - id: banking-service
          uri: lb://BANKING-SERVICE
          predicates:
            - Path=/api/banking/**
          filters:
            - StripPrefix=1

security:
  jwt:
    public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAySwsD24XDZZfVc9rkihW/pZ7zvaOoMgCYoQgmlZpesGPj3nIqi6o5Wt9NgAZTZWsX6FzD97J8O4IkeXshuD5uNHcv7jxaDXnEsajOg21RJZfUj88qrbARTfRDJDN8d/TV+NuHGGuwLcpb5Xsm8ufDb8NibTFDdcpNHmPzs5U8pacy7gOL9KPpoelwqOtluUN6cJxU9v8TiXi23LseGxk35RvEztDwXMrgk4mCCojgjgs46ejIS/nusGzNeN07f7rsPTwinyysBoiwi8pdcOVQnmIfm52KFQek2dyoucC+sVOen9TmP+4HRSYmDr5S2r8Nr6OPlnrEHpZwVPCN+04ywIDAQAB"
    internal-secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    authorization-header: "Authorization"
    internal-auth-header: "X-Internal-Auth"
    token-prefix: "Bearer "

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours
