server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: mdm-service
          uri: lb://MDM-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: banking-service
          uri: lb://BANKING-SERVICE
          predicates:
            - Path=/api/banking/**
          filters:
            - StripPrefix=0

security:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    public-key: "-----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApERMGdiNGoNYk10qFP1N
    IUChpcRoe7flXDpuHcT7E9XH6bD6MAsXir8dgPUp28iNOyV3VdoqsCUhriSLN/Oe
    q9IbPb2nIFbJG8g+qh7cabj/yRMM3aH7/n+zKjAkT09/SLxPsdTRarRe1F19z3fa
    c77dXSbAF0zkE+6nl5HC8KDaud8PwlbxjzAsT7HT4dRQbwEWd9DnhIaGa7O+bDkO
    jjlgueH7Hm2T1NgPyr1Smyh2eDh0vUUKpyhDSrhjRJEDKTRkIie/QAOGwkAfrQc/
    fLCLCtNoCZhG/F8T2n52TTjiTgPBOC24kcKXI8mh+mALTqOBsSLJO9huF3+Wgudt
    lQIDAQAB
    -----END PUBLIC KEY-----
    "
    internal-secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    authorization-header: "Authorization"
    internal-auth-header: "X-Internal-Auth"
    token-prefix: "Bearer "
    expiration: 86400000 # 24 hours
    internal-expiration: 300000 # 5 minutes

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours
