server:
  port: 8082

spring:
  application:
    name: MDM-SERVICE
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:oracle://localhost:1521/XEPDB1
    username: BANKING_USER
    password: BankingPassword123
    ddl-auto: update

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.security: DEBUG
    com.panda.mdmService: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG

security:
  jwt:
    internal-secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    public-key: "-----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApERMGdiNGoNYk10qFP1N
        IUChpcRoe7flXDpuHcT7E9XH6bD6MAsXir8dgPUp28iNOyV3VdoqsCUhriSLN/Oe
        q9IbPb2nIFbJG8g+qh7cabj/yRMM3aH7/n+zKjAkT09/SLxPsdTRarRe1F19z3fa
        c77dXSbAF0zkE+6nl5HC8KDaud8PwlbxjzAsT7HT4dRQbwEWd9DnhIaGa7O+bDkO
        jjlgueH7Hm2T1NgPyr1Smyh2eDh0vUUKpyhDSrhjRJEDKTRkIie/QAOGwkAfrQc/
        fLCLCtNoCZhG/F8T2n52TTjiTgPBOC24kcKXI8mh+mALTqOBsSLJO9huF3+Wgudt
        lQIDAQAB
        -----END PUBLIC KEY-----
        "
    internal-auth-header: "X-Internal-Auth"
    authorization-header: "Authorization"
    token-prefix: "Bearer "