server:
  port: 8082

spring:
  application:
    name: MDM-SERVICE
  main:
    web-application-type: servlet


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.security: DEBUG
    com.panda.mdmService: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG

security:
  jwt:
    internal-secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAySwsD24XDZZfVc9rkihW/pZ7zvaOoMgCYoQgmlZpesGPj3nIqi6o5Wt9NgAZTZWsX6FzD97J8O4IkeXshuD5uNHcv7jxaDXnEsajOg21RJZfUj88qrbARTfRDJDN8d/TV+NuHGGuwLcpb5Xsm8ufDb8NibTFDdcpNHmPzs5U8pacy7gOL9KPpoelwqOtluUN6cJxU9v8TiXi23LseGxk35RvEztDwXMrgk4mCCojgjgs46ejIS/nusGzNeN07f7rsPTwinyysBoiwi8pdcOVQnmIfm52KFQek2dyoucC+sVOen9TmP+4HRSYmDr5S2r8Nr6OPlnrEHpZwVPCN+04ywIDAQAB"
    internal-auth-header: "X-Internal-Auth"
    authorization-header: "Authorization"
    token-prefix: "Bearer "