-- Drop table if exists (Oracle syntax)
DROP TABLE USERS;

-- Create USERS table
CREATE TABLE USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    PHONE VARCHAR2(11),
    TENANT_ID VARCHAR2(50) NOT NULL,
    TENANT_CODE VARCHAR2(50) NOT NULL,
    EMPLOYEE_ID VARCHAR2(50),
    EMPLOYEE_CODE VARCHAR2(50),
    FIRST_NAME VARCHAR2(100),
    LAST_NAME VARCHAR2(100),
    TYPE VARCHAR2(50)
);
